version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-secrets-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=secrets_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fastapi-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: secrets_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
